//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrazilianAddresses.Exceptions.ResourcesMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class APIMSG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APIMSG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrazilianAddresses.Exceptions.ResourcesMessage.APIMSG", typeof(APIMSG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank page, no more records. Go back a page or reduce the number of records per page..
        /// </summary>
        public static string BLANK_PAGE {
            get {
                return ResourceManager.GetString("BLANK_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;City&apos; is a required field..
        /// </summary>
        public static string EMPTY_CITY {
            get {
                return ResourceManager.GetString("EMPTY_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;IBGECode&apos; is a required field..
        /// </summary>
        public static string EMPTY_IBGECODE {
            get {
                return ResourceManager.GetString("EMPTY_IBGECODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;PageIndex&apos; is a required field.
        /// </summary>
        public static string EMPTY_PAGEINDEX {
            get {
                return ResourceManager.GetString("EMPTY_PAGEINDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;PageSize&apos; is a required field.
        /// </summary>
        public static string EMPTY_PAGESIZE {
            get {
                return ResourceManager.GetString("EMPTY_PAGESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;State&apos; is a required field..
        /// </summary>
        public static string EMPTY_STATE {
            get {
                return ResourceManager.GetString("EMPTY_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method executed successfully.
        /// </summary>
        public static string EXECUTION_SUCCESS_MSG {
            get {
                return ResourceManager.GetString("EXECUTION_SUCCESS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city code entered is already registered..
        /// </summary>
        public static string EXISTING_CODE {
            get {
                return ResourceManager.GetString("EXISTING_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location entered was successfully registered..
        /// </summary>
        public static string IBGE_CREATED {
            get {
                return ResourceManager.GetString("IBGE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page index value is too large. Please enter an integer value between 0 and {0}.
        /// </summary>
        public static string INDEX_TOO_LARGE {
            get {
                return ResourceManager.GetString("INDEX_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City entered is not valid..
        /// </summary>
        public static string INVALID_CITY {
            get {
                return ResourceManager.GetString("INVALID_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City code entered is not valid..
        /// </summary>
        public static string INVALID_CODE {
            get {
                return ResourceManager.GetString("INVALID_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageIndex entered value is not valid.
        /// </summary>
        public static string INVALID_PAGEINDEX {
            get {
                return ResourceManager.GetString("INVALID_PAGEINDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSize entered  value is not valid.
        /// </summary>
        public static string INVALID_PAGESIZE {
            get {
                return ResourceManager.GetString("INVALID_PAGESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state reported does not exist..
        /// </summary>
        public static string INVALID_STATE {
            get {
                return ResourceManager.GetString("INVALID_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow error..
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
    }
}
